### ISSUE TITLE
Accessibility issues on some input text components

### ISSUE THREAD

**Issue by sudo-kaizen** [Charlie85270/tail-kit#18]
I discovered that there are some accessibility issues on some of
the form input components at [Input](https://www.tailwind-kit.com/components/inputtext). To be more specific, for the 
following components

1. with label
2. required
3. on error
4. with indications

On clicking the label of these components, the input element is not focused.
This is coming from the absence of an `id` attribute on the input elements
with a value that corresponds with the value of its label's `for` attribute value.

This behaviour is opposed to the *Price* component on the same page which
has these values correct.

Can I raise a PR that resolves this?

**Comment by Charlie85270** [comment]
Hi sudo-kaizen and thanks for the issue ! 

Yes for sure you can do a PR, with pleasure !
