### ISSUE TITLE
Features on mobile

### ISSUE THREAD

**Issue by ciruz** [Charlie85270/tail-kit#20]
Hey Charlie,

found some mobile issues, if I have time I'll help you fixing some of them.

Best Tom

![Screenshot_20210114-232759.jpg](https://user-images.githubusercontent.com/987947/104657139-bed0da00-56c0-11eb-903b-8c07f65b7759.jpg)

**Comment by Charlie85270** [comment]
Fix with commit https://github.com/Charlie85270/tail-kit/commit/9c57b4590d70d3874adcce062eb560b3f9a19a6c
