### ISSUE TITLE
Testimonials on mobile

### ISSUE THREAD

**Issue by ciruz** [Charlie85270/tail-kit#21]
![Screenshot_20210114-233642.jpg](https://user-images.githubusercontent.com/987947/104657544-6b12c080-56c1-11eb-8fc8-ad3c9b74f489.jpg)

Spacing
![Screenshot_20210114-233747.jpg](https://user-images.githubusercontent.com/987947/104657605-88e02580-56c1-11eb-8902-e677840d75ac.jpg)

**Comment by Charlie85270** [comment]
Fix with commit https://github.com/Charlie85270/tail-kit/commit/9c57b4590d70d3874adcce062eb560b3f9a19a6c
