### ISSUE TITLE
Review hidden on mobile

### ISSUE THREAD

**Issue by ciruz** [Charlie85270/tail-kit#22]
![Screenshot_20210114-233852.jpg](https://user-images.githubusercontent.com/987947/104657696-b4fba680-56c1-11eb-9bd2-240005c98093.jpg)

**Comment by Charlie85270** [comment]
Fix with commit https://github.com/Charlie85270/tail-kit/commit/9c57b4590d70d3874adcce062eb560b3f9a19a6c
