### ISSUE TITLE
Big team not responsive

### ISSUE THREAD

**Issue by ciruz** [Charlie85270/tail-kit#23]
![Screenshot_20210114-234037.jpg](https://user-images.githubusercontent.com/987947/104657836-fee48c80-56c1-11eb-8815-9b6b36f7a053.jpg)

**Comment by Charlie85270** [comment]
Fix with commit https://github.com/Charlie85270/tail-kit/commit/9c57b4590d70d3874adcce062eb560b3f9a19a6c
