### ISSUE TITLE
horizontal scrollbar on tablet

### ISSUE THREAD

**Issue by ciruz** [Charlie85270/tail-kit#29]
On a tablet, there's a horizontal scrollbar on the page due the navigation.

![image](https://user-images.githubusercontent.com/987947/105004154-d3e89880-5a33-11eb-918f-053b5d97c581.png)

**Comment by Charlie85270** [comment]
Solve with commit: https://github.com/Charlie85270/tail-kit/commit/292502f5267823613d7acc953727ceedeba0f734
