### ISSUE TITLE
twitter:site should be a twitter username

### ISSUE THREAD

**Issue by ciruz** [Charlie85270/tail-kit#30]
Hey,

the twitter:site attribute:
https://github.com/Charlie85270/tail-kit/blob/7a1d12f6fc2215360c83afa94a8e3cf76cb0e6aa/components/site/Meta.tsx#L23 
should be a twitter @username.

**Comment by Charlie85270** [comment]
Solve with commit: https://github.com/Charlie85270/tail-kit/commit/d57000aa5c6d2d9ce5b4c537cdac2b49226dbc93
