### ISSUE TITLE
feat: tooling

### ISSUE THREAD

**Issue by tomasvn** [Charlie85270/tail-kit#33]
- I have opened a PR regarding this issue, as you have a lot of forks and a lot of people are contributing, I have taken some time to set up tools for this project [PR #19 ](https://github.com/Charlie85270/tail-kit/pull/19)

**Comment by Charlie85270** [comment]
Hi tomasvn and thanks for your PR ! 
I have check it, you're right I need to add the configuration for formatting the code. 
I'm not used to the formatting used in your PR, I'll add mine and the configuration files that go with it. 
I'm sorry I didn't look at your PR earlier but I've been a bit busy lately. 
Anyway, thanks for your contribution!
