### ISSUE TITLE
More Components 

### ISSUE THREAD

**Issue by shubhsk88** [Charlie85270/tail-kit#43]
Are you accepting the component from more users?If it is possible will you consider adding the checkout form or different cards in your library if so please let me know I will be happy to add those in the library. Please let me know

**Comment by Charlie85270** [comment]
Hi shubhsk88, 

Yes you can add any components of your choice, the only conditions are :
- Responsive
- Coded only with Tailwind CSS 2.0 classes
- Filed in the right category
- Design is subjective, all styles are accepted but code of the components/templates must be clean

If you want add components or templates, just do a PR and I will review it :) 
I have updated the readme to explain how to create new components/templates.

**Comment by shubhsk88** [comment]
Thanks I will open a PR as soon as I am done with it
