### ISSUE TITLE
Putting all import of every Kit in the index file

### ISSUE THREAD

**Issue by shubhsk88** [Charlie85270/tail-kit#47]
Is it possible to put all imports of the kit of each section as an index file and then import in the page file from one file?

**Comment by Charlie85270** [comment]
Hi shubhsk88,

I will think of a simpler and cleaner way of doing this. This will come with documentation on commit rules, adding components, code formatting etc...
I admit that I haven't worked on that yet and the project is still fresh. 
I will work on this ! 

Thanks for your feedback,

Charlie

**Comment by shubhsk88** [comment]
Let me know if you need any help I have experience in nextjs
