### ISSUE TITLE
tail-kit components navi is off-screen

### ISSUE THREAD

**Issue by ciruz** [Charlie85270/tail-kit#50]
Hey on a laptop with MDPI Screen (1280x800) the components navi is outside of the screen:

![image](https://user-images.githubusercontent.com/987947/106149560-b37ab580-617a-11eb-82e3-15beb5098722.png)

**Comment by Charlie85270** [comment]
Resolve with commit : https://github.com/Charlie85270/tail-kit/commit/ac723d426fc4b8bad23bd06ea65960f8c156da6f
