### ISSUE TITLE
Toggle button transition not working

### ISSUE THREAD

**Issue by amaan-ahmad** [Charlie85270/tail-kit#54]
Hey contributors, 

I tried fixing the transition in the toggle button, but it doesn't seem to work.

The reason is: 
- transition class name in tailwind does transition on the following properties: 
  - background-color
  - border-color
  - color
  - fill
  - stroke
  - opacity
  - box-shadow
  - transform

We need to apply transition on the position because the toggle element takes ```checked: right-0```.

It would be great if someone could figure out how to apply transition on "position" property.

Thanks,
Amaan Ahmad.

**Comment by wanacode** [comment]
I managed to get a transition on the toggle by adding a class to set the initial position ```right-4``` and then a transition duration e.g. ```duration-300```. 

Without an initial value for ```right``` being set, the toggle doesn't have a value to transition _from_, so it can't animate the element.

**Comment by amaan-ahmad** [comment]
Great! If it's working then kindly do a PR. It will be reviewed by Maintainer.

**Comment by wanacode** [comment]
Sure, I have created a PR to resolve this: https://github.com/Charlie85270/tail-kit/pull/56

**Comment by Charlie85270** [comment]
Fix with : https://github.com/Charlie85270/tail-kit/pull/56
