### ISSUE TITLE
How use tsx component in Vuejs project

### ISSUE THREAD

**Issue by Sorrow81** [Charlie85270/tail-kit#55]
Hello,

First, thanks for you awesome works !

How can I use Navbar with JS in Nuxtjs project ? Do i need to adapt the react component, or it's possible with other way ?

Thanks for you support.

**Comment by Charlie85270** [comment]
Hi Sorrow and thanks for the support ! 

Yes you need to adapt the react component for VueJS.
If you want help don't hesitate to contact me ;) 

Charlie
