### ISSUE TITLE
vanilla js?

### ISSUE THREAD

**Issue by Lolosan** [Charlie85270/tail-kit#60]
How to use tail-kit with normal html + js?

Components are asking for react, like DropDownMenu.tsx

**Comment by yhdesai** [comment]
Use a JSX to HTML Converter to convert the code inside the return function to HTML, then you'll be able to use it in vanilla HTML + JS

**Comment by Charlie85270** [comment]
Hey @Lolosan , components are coded with JSX and "transformed" to pure HTML for the design part, you can find them on the code editor. 
Regarding the JS, as @yhdesai said, the best solution is to convert the "react" functions to native vanilla JS. I don't see/know "easy" solution to do that. And develop all components with react + vanilla JS is a big job and isn't the main goal of the application.
