### ISSUE TITLE
Mobile view is breaking of Teams > Multiple

### ISSUE THREAD

**Issue by xerosanyam** [Charlie85270/tail-kit#65]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/3167278/124593641-809cc200-de7c-11eb-8ed9-4cd8f4fce9fe.png">

Actual: Image of 2nd team mate is hiding the social information present on card of 1st team mate.
Expectation: Image of 2nd team mate must be below the card of 1st team mate.

**Comment by gitryder** [comment]
Is this assigned to anyone? If not, I would like to work on it.

**Comment by xerosanyam** [comment]
hey @gitryder! Thanks but I already have a pr in place
https://github.com/Charlie85270/tail-kit/pull/66

can you review & suggest if any changes are required?

**Comment by gitryder** [comment]
Sure @xerosanyam, I'll take a look. Thanks for replying! 😃
