### ISSUE TITLE
[feature] Upgrade to Tailwindcss 3

### ISSUE THREAD

**Issue by bingalls** [Charlie85270/tail-kit#78]
I started a fork, to upgrade TailKit to Tailwindcss 3, but ran into problems, some of which are documented in my README.md
* lint fails for the `build/` directory. It should likely be excluded.
* Cannot upgrade Node past v14 because of Webpack 4.
* Cannot upgrade React & dependencies past v16 because of react-simple-code-editor v0.11.0

The biggest problem is that Tailwind 3 requires PostCss 8 & Autoprefixer >=10. You'll notice this in
`Error: true is not a PostCSS plugin`.

Here are some links with details:
* https://github.com/postcss/postcss/issues/1420
* https://github.com/tailwindlabs/tailwindcss/issues/2396
* https://github.com/vercel/next.js/issues/17236

Happy bug hunting!

**Comment by bingalls** [comment]
@Charlie85270 https://github.com/Charlie85270/tail-kit/pull/80 should close this feature request.

**Comment by bingalls** [comment]
Wow!
https://github.com/Charlie85270/tail-kit/pull/80/checks?sha=3d625dcd664361f5b98ea80c4296c258fdba6721
CI succeeds. Then I modify & push README.md, and
https://github.com/Charlie85270/tail-kit/pull/80/checks?sha=61244deaddcfcfc683579eced9024efc066d1b90
fails. Go figure.

**Comment by hanumanjiblog** [comment]
Please Upgrade As Soon as possible

**Comment by bingalls** [comment]
As a OSS project, this is entitled to a free upgrade from https://laravelshift.com/upgrade-tailwind-css-2-to-tailwind-css-3
However, it really requires @Charlie85270  to set this up in this original repository.
This should make it easier for us, including @hanumanjiblog & I to finish the upgrade.

**Comment by Charlie85270** [comment]
Hey guys ! Sorry for my late answer and reaction, I'm back ! 

I finally upgraded the project with Tailwind CSS v3 !  
Closed with https://github.com/Charlie85270/tail-kit/commit/bf5c63613dbc2246d39d7519a7ee6f4236060397
