### ISSUE TITLE
Your Google Auto Ads breaks the website experience

### ISSUE THREAD

**Issue by ghostzero** [Charlie85270/tail-kit#83]
Hey,

The Google Auto Ads are pretty much breaking your website. With it, your components can't be seen properly. It's also annoying to have an ad every fourth component. That's just as much toxic advertising density as Instagram or Twitter.

Through the Ad Spam you have lost me but I am kind enough to open an issue here.

![image](https://user-images.githubusercontent.com/6547306/175394805-ea6c3e1e-3b20-4edf-9b3d-2b438a00e019.png)
![image](https://user-images.githubusercontent.com/6547306/175395236-db28ecc5-605c-4adf-af57-2993d8a7cf7f.png)

**Comment by Charlie85270** [comment]
Hey @ghostzero , I finally removed all the publicities !
